import { useState } from 'react'
import { FilePlus2, ShieldCheck } from 'lucide-react'
import { Button } from '@/components/ui/Button'
import { EmptyState, Toast } from '@/components/ui/Feedback'
import { PageHeader } from '@/components/shared/PageHeader'
import { RecordCard, RecordDetailModal } from '@/components/shared/Record'
import { AddRecordModal } from '@/components/shared/AddRecordModal'
import { patientRecords, recordById, type RecordType } from '@/data/records'
import { cn } from '@/lib/utils'

const filters: { label: string; types: RecordType[] | null }[] = [
  { label: 'All', types: null },
  { label: 'Consultations', types: ['Consultation'] },
  { label: 'Prescriptions', types: ['Prescription'] },
  { label: 'Reports', types: ['Report'] },
  { label: 'Hospital Records', types: ['Hospital Record'] },
  { label: 'Investigations', types: ['Investigation'] },
  { label: 'Referrals', types: ['Referral'] },
  { label: 'Other', types: ['Other'] },
]

export default function PatientRecords() {
  const [filter, setFilter] = useState('All')
  const [record, setRecord] = useState<string | null>(null)
  const [addOpen, setAddOpen] = useState(false)
  const [source, setSource] = useState<'All' | 'Organisation' | 'Patient'>('All')
  const [toast, setToast] = useState<string | null>(null)

  const showToast = (msg: string) => {
    setToast(msg)
    setTimeout(() => setToast(null), 3500)
  }

  const active = filters.find((f) => f.label === filter)!
  const list = patientRecords
    .filter((r) => !active.types || active.types.includes(r.type))
    .filter((r) => source === 'All' || r.source === source)

  const organCount = patientRecords.filter((r) => r.source === 'Organisation').length

  return (
    <div className="space-y-6">
      <PageHeader
        title="Records"
        description={
          <span className="flex items-center gap-1.5">
            <ShieldCheck className="size-4 text-brand-600" />
            The healthcare information behind your timeline events. {organCount} generated by organisations,{' '}
            {patientRecords.length - organCount} provided by you.
          </span>
        }
      >
        <Button onClick={() => setAddOpen(true)}>
          <FilePlus2 className="size-4.5" />
          Add record
        </Button>
      </PageHeader>

      <div className="flex flex-wrap items-center justify-between gap-3">
        <div className="flex flex-wrap gap-2">
          {filters.map((f) => (
            <button
              key={f.label}
              onClick={() => setFilter(f.label)}
              className={cn(
                'rounded-full px-4 py-2 text-sm font-semibold transition',
                filter === f.label
                  ? 'bg-brand-600 text-white shadow-sm'
                  : 'bg-white text-slate-600 ring-1 ring-slate-200 hover:bg-slate-50',
              )}
            >
              {f.label}
            </button>
          ))}
        </div>
        <div className="flex gap-2">
          {(['All', 'Organisation', 'Patient'] as const).map((s) => (
            <button
              key={s}
              onClick={() => setSource(s)}
              className={cn(
                'rounded-full px-3 py-1.5 text-xs font-semibold transition',
                source === s
                  ? 'bg-navy-600 text-white'
                  : 'bg-white text-slate-500 ring-1 ring-slate-200 hover:bg-slate-50',
              )}
            >
              {s === 'All' ? 'Any source' : s === 'Organisation' ? 'Org generated' : 'Patient provided'}
            </button>
          ))}
        </div>
      </div>

      {list.length === 0 ? (
        <EmptyState
          title="No records of this type"
          description="Try a different filter, or add an old or external record yourself."
          action={
            <Button onClick={() => setAddOpen(true)}>
              <FilePlus2 className="size-4.5" />
              Add record
            </Button>
          }
        />
      ) : (
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {list.map((r) => (
            <RecordCard key={r.id} record={r} onOpen={() => setRecord(r.id)} />
          ))}
        </div>
      )}

      <AddRecordModal
        open={addOpen}
        onClose={() => setAddOpen(false)}
        onSaved={(note) => {
          setAddOpen(false)
          showToast(note)
        }}
      />

      <RecordDetailModal record={record ? recordById(record) ?? null : null} onClose={() => setRecord(null)} />

      {toast ? (
        <div className="fixed bottom-6 right-6 z-50">
          <Toast message={toast} />
        </div>
      ) : null}
    </div>
  )
}